source_list:
#  - SB
#  - OL
  - CP
#  - ADDR

s3_conf:
  s3_bucket: dataframe8790
  staging_dir: staging

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id

OL:
  sftp_conf:
      filetype: csv
      delimiter: |
      directory: /home/ubuntu/data

ADDR:
  mongodb_config:
    database: customer
    collection: address
CP:
  filename: /data/KC_Extract_1_20171009.csv

redshift_conf:
  filetype: csv
  delimiter: |

REGIS_DIM:
  tableName: DATAMART.REGIS_DIM
  source_data:
    - CP
    - ADDR
  loadingQuery: >
    SELECT
      MONOTONICALLY_INCREASING_ID() AS REGIS_KEY, REGIS_CNSM_ID AS CNSM_ID,REGIS_CTY_CODE AS CTY_CODE,
      REGIS_ID, REGIS_DATE, REGIS_LTY_ID AS LTY_ID, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, INS_DT
    FROM
      (SELECT
        DISTINCT REGIS_CNSM_ID, CAST(REGIS_CTY_CODE AS SMALLINT), CAST(REGIS_ID AS INTEGER),
        REGIS_LTY_ID, REGIS_DATE, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, B.street, B.City, B.state, , INS_DT
      FROM
        CP A JOIN ADDR B A.REGIS_CNSM_ID = B.consumer_id
      WHERE
        INS_DT = CURRENT_DATE
      ) CP

