source_list:
#  - SB
  - OL
#  - CP
#  - ADDR

s3_conf:
  s3_bucket: dataframe8790
  staging_dir: staging

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id

OL:
  sftp_conf:
      filetype: csv
      delimiter: |
      directory: /home/ubuntu/data

ADDR:
  mongodb_config:
    database: customer
    collection: address
CP:
  filename: kk
redshift_conf:
  filetype: csv
  delimiter: |

